version: '3'

services:

  nginx:
    image: nginx:alpine
    container_name: coolstuff_solutions_nginx
    ports:
      - "9700:80"
    volumes:
      - ./app:/var/www
      - ./sys/nginx:/etc/nginx/conf.d/
    networks:
      coolstuff-solutions:
        aliases:
          - nginx

  app:
    build:
      context: .
      dockerfile: sys/php/Dockerfile
    image: coolstuff_solutions:app
    container_name: coolstuff_solutions_app
    env_file:
      - app/.env
    environment:
      APP_NAME: "CoolStuff Solutions"
    working_dir: /var/www
    volumes:
      - ./app:/var/www
      - ./app/var/:/var/www/var:rw
      - ./sys/php/default.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      coolstuff-solutions:
        aliases:
          - app

  mysql:
    image: mysql:8.0
    container_name: coolstuff_solutions_rdbms
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: coolstuff_solutions_db
      MYSQL_USER: developer
      MYSQL_PASSWORD: root
    ports:
      - "9701:3306"
    volumes:
      - /var/lib/mysql
      - ./sys/mysql/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      coolstuff-solutions:
        aliases:
          - mysql

  smtp:
    platform: linux/x86_64
    image: mailhog/mailhog
    container_name: coolstuff_solutions_smtp
    logging:
      driver: 'none'
    ports:
      - "9702:1025"
      - "9703:8025"
    networks:
      coolstuff-solutions:
        aliases:
           - smtp

  phpmyadmin:
    image: phpmyadmin:5.2.0
    container_name: coolstuff_solutions_phpmyadmin
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "9704:80"
    networks:
      coolstuff-solutions:
        aliases:
          - phpmyadmin

  testing_db:
    image: mysql:5.7
    container_name: coolstuff_solutions_testind_db
    environment:
      MYSQL_ROOT_PASSWORD: 'testing'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_RANDOM_ROOT_PASSWORD: 0
      MYSQL_DATABASE: 'coolstuff_solutions_testing_db'
      MYSQL_USER: 'testuser'
      MYSQL_PASSWORD: 't3st!n6'
    tmpfs:
      - /var/lib/mysql
    networks:
      coolstuff-solutions:
        aliases:
          - testing_db

networks:
  coolstuff-solutions:
    name: coolstuff-solutions
    driver: bridge

volumes:
  storage:
    driver: local